version: '3.1'

services:

  source_db:
    image: mysql:8.0.34
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - 3310:3306

  data_warehouse:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5410:5432

  metabase:
    image: metabase/metabase:v0.46.8
    container_name: metabase
    hostname: metabase
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: warehouse
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: data_warehouse
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5